env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1 # switch case 的缩进，是前一字段的多少倍
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - error
    - allow:
      - warn
      - error
      - log
